// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThiHuong668.Data;

namespace NguyenThiHuong668.Migrations
{
    [DbContext(typeof(NguyenThiHuong668Context))]
    [Migration("20211006003300_NTH0668")]
    partial class NTH0668
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NguyenThiHuong668.Models.NTH0668", b =>
                {
                    b.Property<string>("NTHId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NTHGende")
                        .HasColumnType("boolean");

                    b.Property<string>("NTHName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NTHId");

                    b.ToTable("NTH0668");
                });

            modelBuilder.Entity("NguyenThiHuong668.Models.PersonNTH668", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonId");

                    b.ToTable("PersonNTH668");
                });
#pragma warning restore 612, 618
        }
    }
}
